export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_TRAILER = "GET_MOVIE_TRAILER";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const GET_GENRES = "GET_GENRES";
export const GET_MOVIES_BY_GENRE = "GET_MOVIES_BY_GENRE";